export const villas = [
    {
        key: "ivanka",
        name: "Villa Ivanka",
        bedrooms: 1,
        bathrooms: 2,
        maxGuests: "2",
    },
    {
        key: "milka",
        name: "Villa Milka",
        bedrooms: 2,
        bathrooms: 1,
        maxGuests: "4 + 2",
    },
    {
        key: "vesna",
        name: "Villa Vesna",
        bedrooms: 4,
        bathrooms: 4,
        maxGuests: "6 + 2",
    },
] as const;

export const villaIvankaImages = [
    "/villas/ivanka/1.jpg",
    "/villas/ivanka/2.jpg",
    "/villas/ivanka/3.jpg",
    "/villas/ivanka/4.jpeg",
    "/villas/ivanka/5.jpeg",
    "/villas/ivanka/6.jpeg",
    "/villas/ivanka/7.jpeg",
    "/villas/ivanka/8.jpeg",
    "/villas/ivanka/9.jpeg",
    "/villas/ivanka/10.jpeg",
    "/villas/ivanka/11.jpeg",
    "/villas/ivanka/12.jpeg",
    "/villas/ivanka/13.jpeg",
    "/villas/ivanka/14.jpeg",
    "/villas/ivanka/15.jpeg",
    "/villas/ivanka/16.jpeg",
    "/villas/ivanka/17.jpeg",
    "/villas/ivanka/18.jpeg",
] as const;

export const villaMilkaImages = [
    "/villas/milka/1.jpg",
    "/villas/milka/2.jpg",
    "/villas/milka/3.jpg",
    "/villas/milka/4.jpeg",
    "/villas/milka/5.jpeg",
    "/villas/milka/6.jpeg",
    "/villas/milka/7.jpeg",
    "/villas/milka/8.jpeg",
    "/villas/milka/9.jpeg",
    "/villas/milka/10.jpeg",
    "/villas/milka/11.jpeg",
    "/villas/milka/12.jpeg",
    "/villas/milka/13.jpeg",
    "/villas/milka/14.jpeg",
    "/villas/milka/15.jpeg",
    "/villas/milka/16.jpeg",
    "/villas/milka/17.jpeg",
    "/villas/milka/18.jpeg",
    "/villas/milka/19.jpeg",
    "/villas/milka/20.jpeg",
    "/villas/milka/21.jpeg",
    "/villas/milka/22.jpeg",
    "/villas/milka/23.jpeg",
] as const;

export const villaVesnaImages = [
    "/villas/vesna/1.jpg",
    "/villas/vesna/2.jpg",
    "/villas/vesna/3.jpg",
    "/villas/vesna/4.jpeg",
    "/villas/vesna/5.jpeg",
    "/villas/vesna/6.jpeg",
    "/villas/vesna/7.jpeg",
    "/villas/vesna/8.jpeg",
    "/villas/vesna/9.jpeg",
    "/villas/vesna/10.jpeg",
    "/villas/vesna/11.jpeg",
    "/villas/vesna/12.jpeg",
    "/villas/vesna/13.jpeg",
    "/villas/vesna/14.jpeg",
    "/villas/vesna/15.jpeg",
    "/villas/vesna/16.jpeg",
    "/villas/vesna/17.jpeg",
    "/villas/vesna/18.jpeg",
    "/villas/vesna/19.jpeg",
    "/villas/vesna/20.jpeg",
    "/villas/vesna/21.jpeg",
    "/villas/vesna/22.jpeg",
] as const;

export const villaImagesByName = {
    "Villa Ivanka": villaIvankaImages,
    "Villa Milka": villaMilkaImages,
    "Villa Vesna": villaVesnaImages,
} as const;
